def classfromName(field):
    dictionary = {'Abandoned':'Abandoned',
    'Academy':'Academy',
    'Administrative':'Government Office',
    'Bank':'Bank',
    'Bata Show Room':'Shop',
    'Brick Field':'Brick Field',
    'Bus Counter':'Service',
    'Bus Terminal':'Bus Terminal',
    'Camp':'Camp',
    'Church':'Church',
    'Cinema Hall':'Cinema Hall',
    'Circulation Network':'Circulation Network',
    'Clinic':'Clinic',
    'Club':'Club',
    'Coaching Center':'Coaching Center',
    'Cogulation Cember':'Cogulation Cember',
    'College':'College',
    'Committee':'Committee',
    'Community Facilities':'Community Facilities',
    'Conference Room':'Auditorium',
    'Control Room':'Service',
    'Cummunity Facility':'Cummunity Facility',
    'Dust Bin':'Dust Bin',
    'Education and Research':'School',
    'Eidgah':'Eidgah',
    'Factory':'Factory',
    'Farm':'Farm',
    'Filling Station':'Filling Station',
    'Food Company':'Company',
    'Garage':'Garage',
    'Generator Room':'Service',
    'Godown':'Godown',
    'Government Office':'Government Office',
    'Guard Room':'Service',
    'Health Complex':'Health Complex',
    'High School':'High School',
    'Hospital':'Hospital',
    'Hostel':'Hostel',
    'Hotel':'Hotel',
    'House':'House',
    'Industry':'Industry',
    'Institution':'Institution',
    'Jail':'Jail',
    'Kindergarten School':'Kindergarten School',
    'Laboratory':'Laboratory',
    'Library':'Library',
    'Madrashah':'Madrashah',
    'Majar':'Majar',
    'Maktab':'Madrashah',
    'Market':'Market',
    'Mill':'Mill',
    'Miscellaneous':'Miscellaneous',
    'Mixed Use':'Mixed Use',
    'Mobile Tower Station':'Service',
    'Monument':'Monument',
    'Mosque':'Mosque',
    'NGO':'NGO',
    'Office':'Office',
    'Others':'Others',
    'Park':'Park',
    'Parking lot':'Parking lot',
    'Paurashava':'Paurashava',
    'Pitha Ghor':'Shop',
    'Police Box':'Police Box',
    'Police Station':'Police Station',
    'Post Office':'Post Office',
    'Poultry Firm':'Farm',
    'Power Plant':'Power Plant',
    'Pre Cadet School':'Pre Cadet School',
    'Primary School':'Primary School',
    'Public Toilet':'Service',
    'Pump House':'Service',
    'Quarter':'Quarter',
    'Religious':'Religious',
    'Residential':'House',
    'Rest House':'House',
    'Saloon':'shop',
    'Saw Mill':'Mill',
    'Security Room':'Service',
    'School':'School',
    'Sedimentation Tank':'Service',
    'Sitting space':'Community Facilities',
    'Service':'Service',
    'Shop':'Shop',
    'Slum':'House',
    'SP office':'Government Office',
    'Stadium':'Stadium',
    'Stage':'Others',
    'Store Room':'Godown',
    'Tea Stall':'Shop',
    'Temple':'Temple',
    'Ticket Counter':'Ticket Counter',
    'Toilet':'Service',
    'Tower':'Service',
    'Town Hall':'Town Hall',
    'Training Center':'Training Center',
    'Transport & Communication':'Service',
    'UC':'Under Construction',
    'Under Construction':'Under Construction',
    'Union Parishad':'Union Parishad',
    'University':'University',
    'Waiting Shed':'Service',
    'Water Pamp':'Community Facilities',
    'Water Plant':'Service',
    'Water Tank':'Service',
    'Workshop':'Shop'}
    return dictionary.get(field,'undefined')