# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# photo to map.py
# Created on: 2018-01-23 08:10:29.00000
#   (generated by ArcGIS/ModelBuilder)
# Usage: photo to map <Pictures> <Pictures_GeoTaggedPhotosToPo> <invalid> 
# Description: 
# Adds geotagged photos to map
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy

# Script arguments
Pictures = arcpy.GetParameterAsText(0)
if Pictures == '#' or not Pictures:
    Pictures = "C:\\Users\\mizan_admin\\SHAREit\\Pictures" # provide a default value if unspecified

Pictures_GeoTaggedPhotosToPo = arcpy.GetParameterAsText(1)
if Pictures_GeoTaggedPhotosToPo == '#' or not Pictures_GeoTaggedPhotosToPo:
    Pictures_GeoTaggedPhotosToPo = "C:\\Users\\mizan_admin\\Documents\\ArcGIS\\Default.gdb\\Pictures_GeoTaggedPhotosToPo" # provide a default value if unspecified

invalid = arcpy.GetParameterAsText(2)
if invalid == '#' or not invalid:
    invalid = "C:\\Users\\mizan_admin\\Documents\\ArcGIS\\Default.gdb\\invalid" # provide a default value if unspecified

# Local variables:

# Process: GeoTagged Photos To Points
arcpy.GeoTaggedPhotosToPoints_management(Pictures, Pictures_GeoTaggedPhotosToPo, invalid, "ALL_PHOTOS", "ADD_ATTACHMENTS")

